name: 0 - Run Everything


on:
  workflow_dispatch:
  push:
    branches: [main]


jobs:
  test_django:
    uses: ./.github/workflows/test.yaml
    secrets:
      DJANGO_SECRET_KEY: "${{ secrets.DJANGO_SECRET_KEY }}"
  build_django:
    needs: test_django
    uses: ./.github/workflows/container.yaml
    secrets:
      DOCKERHUB_USERNAME: "${{ secrets.DOCKERHUB_USERNAME }}"
      DOCKERHUB_PASSWORD: "${{ secrets.DOCKERHUB_PASSWORD }}"
      DOCKER_APPNAME: "${{ secrets.DOCKER_APPNAME }}"
  update_infra:
   needs: build_django
   uses: ./.github/workflows/infra.yaml
   secrets:
     #ALLOWED_HOST: ${{ secrets.ALLOWED_HOST }}
     DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
     DB_CERT_FILE: ${{ secrets.DB_CERT_FILE }}
     DJANGO_DEBUG: ${{ secrets.DJANGO_DEBUG }}
     DJANGO_VM_COUNT: ${{ secrets.DJANGO_VM_COUNT }}
     DOCKER_APPNAME: ${{ secrets.DOCKER_APPNAME }}
     DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
     OBJECT_STORAGE_REGION: ${{ secrets.OBJECT_STORAGE_REGION }}
     OBJECT_STORAGE_ACCESS_KEY: ${{ secrets.OBJECT_STORAGE_ACCESS_KEY }}
     OBJECT_STORAGE_SECRET_KEY: ${{ secrets.OBJECT_STORAGE_SECRET_KEY }}
     DEVOPS_IMAGE: ${{ secrets.DEVOPS_IMAGE }}
     OBJECT_STORAGE_DEVOPS_BUCKET: ${{ secrets.OBJECT_STORAGE_DEVOPS_BUCKET }}
     OBJECT_STORAGE_DEVOPS_TF_KEY: ${{ secrets.OBJECT_STORAGE_DEVOPS_TF_KEY }}
     OBJECT_STORAGE_DEVOPS_REGION: ${{ secrets.OBJECT_STORAGE_DEVOPS_REGION }}
     OBJECT_STORAGE_DEVOPS_ENDPOINT: ${{ secrets.OBJECT_STORAGE_DEVOPS_ENDPOINT }}
     OBJECT_STORAGE_DEVOPS_ACCESS_KEY: ${{ secrets.OBJECT_STORAGE_DEVOPS_ACCESS_KEY }}
     OBJECT_STORAGE_DEVOPS_SECRET_KEY: ${{ secrets.OBJECT_STORAGE_DEVOPS_SECRET_KEY }}
     OBJECT_STORAGE_BUCKET: ${{ secrets.OBJECT_STORAGE_BUCKET }}
     OBJECT_STORAGE_PA_TOKEN: ${{ secrets.OBJECT_STORAGE_PA_TOKEN }}
     DATABASE_BACKEND: ${{ secrets.DATABASE_BACKEND }}
     POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
     POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
     POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
     POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
     POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
     DJANGO_STORAGE_SERVICE: ${{ secrets.DJANGO_STORAGE_SERVICE }}
     DO_SSH_KEY_ID: ${{ secrets.DO_SSH_KEY_ID }}
     #SSH_PUB_KEY: ${{ secrets.SSH_PUB_KEY }}
     SSH_DEVOPS_KEY_PUBLIC: "${{ secrets.SSH_DEVOPS_KEY_PUBLIC }}"
     SSH_DEVOPS_KEY_PRIVATE: "${{ secrets.SSH_DEVOPS_KEY_PRIVATE }}"

  collect_static:
    needs: test_django
    uses: ./.github/workflows/collectstatic.yaml
    secrets:
      DJANGO_DEBUG: ${{ secrets.DJANGO_DEBUG }}
      DJANGO_SECRET_KEY: "${{ secrets.DJANGO_SECRET_KEY }}"
      OBJECT_STORAGE_BUCKET: "${{ secrets.OBJECT_STORAGE_BUCKET }}"
      OBJECT_STORAGE_REGION: "${{ secrets.OBJECT_STORAGE_REGION }}"
      OBJECT_STORAGE_ACCESS_KEY: "${{ secrets.OBJECT_STORAGE_ACCESS_KEY }}"
      OBJECT_STORAGE_SECRET_KEY: "${{ secrets.OBJECT_STORAGE_SECRET_KEY }}"
      DATABASE_BACKEND: "${{ secrets.DATABASE_BACKEND }}"
      DJANGO_STORAGE_SERVICE: "${{ secrets.DJANGO_STORAGE_SERVICE }}"
      DJANGO_ROOT_NAME: "${{ secrets.DJANGO_ROOT_NAME }}"
